[workspace]
resolver = "2"

members = [
    "annotations",
    "checker",
    "standard_contracts",
    "contracts/arithmetic",
    "contracts/reentrancy/basis", 
    "contracts/reentrancy/cross_function", 
    "contracts/bad_randomness/random_winner", 
    "contracts/bad_randomness/random_number", "contracts/numerical_precision/basic"]

[profile.release]
debug = true

[profile.bench]
debug = true
