[workspace]
resolver = "2"

members = [
    "annotations",
    "checker",
    "standard_contracts",
    "contracts/reentrancy/basis", 
    "contracts/reentrancy/cross_function", 
    "contracts/time_manipulation/random_winner", 
    "contracts/time_manipulation/random_number", 
    "contracts/numerical_precision/basic", 
    "contracts/numerical_precision/lending", 
    "contracts/arithmetic/lamport_deposit", 
    "contracts/bad_randomness/basic"]

[profile.release]
debug = true

[profile.bench]
debug = true
