[workspace]
resolver = "2"

members = [
    "annotations",
    "checker",
    "standard_contracts",
    "contracts/arithmetic",
    "contracts/reentrancy/basis", 
    "contracts/reentrancy/cross_function"]

[profile.release]
debug = true

[profile.bench]
debug = true
